### ISSUE TITLE
max. Font-Size

### ISSUE THREAD

**Issue by lutzh86** [pi3d/pi3d.github.com#6] opened 2019-01-15 13:12 UTC
hello,

first: thanks for this great project :-)

i am working on an thermostat gui and we need a bigger font size then "0.99" to show the temperature.
i am able to get a bigger font size, but then the quality of each letter goes down and anti-aliasing is visible.

is there an simple way to get bigger letters with TTF font in high quality?

best regards
Lutz

**Comment by paddywwoof** [comment] 2019-01-15 13:34
Hi, glad you're finding it useful. Yes this rings a bell from looking at this ages ago... so it probably does need sorting out.

I think the problem is that the font is rendered by drawing the letters onto a Texture, which is set at 1024x1024, then dividing it up into 256 squares 64x64. This means that the max resolution of each character becomes 54x54 pixels (to allow rotation without getting extraneous corners of adjacent characters)

So there are two directions possible: 1. allow 1920x1920 textures or (better) 2. allow variable division of the area i.e. 16 characters 256x256 or 64 at 128x128

There are a couple of other minor fixes in the develop branch that need pushing to a new release so I will have a look at this issue this afternoon and try to get something working.

**Comment by lutzh86** [comment] 2019-01-15 15:02
![img_20190115_153152](https://user-images.githubusercontent.com/45604968/51188682-ba5d6500-18de-11e9-9e79-6eb013444d69.jpg)

but my first version still looks not bad :-)

i still need to figure out the white line on the bottom (background is 800x480 like image)

**Comment by paddywwoof** [comment] 2019-01-15 20:46
@lutzh86, that looks pretty good. I'll have a look at the line at the bottom issue too - I think that's been there for a long time so it probable does need fixing. Also the outline functionality.

I've pushed up a fix for the higher resolution Font issue to the [develop branch](https://github.com/tipam/pi3d/commit/f605bff45722cc66b76e0f8bfbd732d563215ca6) I will hold off moving to a new version number until I've looked into the other points above.

**Comment by lutzh86** [comment] 2019-01-15 20:59
oh cool, thanks :)  i have a small amount of thermostats ready in a few days, i would like to thank u and send u one

its made for EU - i am not sure about size of uk wall boxes. is there an way to contact u?

![img_20181204_143427](https://user-images.githubusercontent.com/45604968/51209459-8b5fe700-1910-11e9-9c21-80c020394032.jpg)

**Comment by paddywwoof** [comment] 2019-01-16 09:46
Hi, not sure what happened to the reply I thought I sent previously. It's showing in my sent box but hasn't turned up here. This is what it said.

> I'd love to see your thermostat but, seriously, only think about sending one if you really have a surplus of prototypes. You can contact me: patrick at eldwick dot org dot uk.
> 
> How are you doing your background image (i.e. ImageSprite, Sprite, Plane etc) w.r.t. finding what's causing the line at the edge. Does the line always seem to be a solid colour (and or the same colour) or might it be 'wrapping' from the opposite edge?
> 
> Paddy
> 

As an appendix to  my last question... If the line is due to slight rounding of the texture sampling getting pixels from the opposite edge (default tiling is normal repeat) then you could try setting the tiling to mirror repeat - which is an option in OpenGL. Do this in pi3d something like:

```
flatsh = pi3d.Shader('uv_flat')
bkg_tex = pi3d.Texture('textures/world_map.jpg', m_repeat=True)
bkg = pi3d.ImageSprite(bkg_tex, shader=flatsh, camera=CAMERA, w=800, h=480)
```

`ImageSprite.__init__()` doesn't have the facility to pass the extra Texture arguments on but it will accept a Texture instance (as alternative to a path string).

Let me know if this fixes the problem or if I need to look elsewhere. I've a couple of ideas on the outlines but nothing specific yet.

Paddy

**Comment by lutzh86** [comment] 2019-01-16 10:34
i'll get 100 prototypes in a few days :-) and i really appreciate your effort.  

i attached the code regarding to background and fading, i am sure its not optimal, i tried to make an version with low cpu consumption, because background change is not so often 



`def tex_load(fname):

  slide = Slide()
  tex = pi3d.Texture(fname, blend=True, mipmap=False)
  xrat = DISPLAY.width/tex.ix
  yrat = DISPLAY.height/tex.iy
  if yrat < xrat:
    xrat = yrat
  wi, hi = tex.ix * xrat, tex.iy * xrat
  xi = (DISPLAY.width - wi)/2
  yi = (DISPLAY.height - hi)/2
  slide.dimensions = (wi, hi, xi, yi)
  slide.set_texture(tex)
  slide.set_alpha(0.0) 
  slide.set_shader(shader)
  slide.positionZ(0.5)
  slide.set_2d_size(w=wi, h=hi, x=xi, y=yi)
  return slide



class Slide(pi3d.Canvas):
  def __init__(self):
    super(Slide, self).__init__()


DISPLAY = pi3d.Display.create(background=(0.0, 0.0, 0.0, 1.0),
                                frames_per_second=5, tk=False)


shader = pi3d.Shader("2d_flat")     #background is only completely visible with 2d_flat, with uv_flat its an small triangle    
shader2 = pi3d.Shader("uv_flat")   #font works only with uv_flat  
CAMERA = pi3d.Camera(is_3d=False) 
CAMERA = pi3d.Camera.instance()
CAMERA.was_moved = False
nexttm = 0.0
nextsecond = 0.0
sfg = tex_load(iFiles[pic_num])

while DISPLAY.loop_running():
    
    tm = time.time()
    if tm > nexttm: 
     nexttm = tm + TMDELAY
     a = 0.0 
     sbg = sfg
     sbg.positionZ(0.6)
     pic_num = (pic_num + 1) % nFi
     sfg = tex_load(iFiles[pic_num]) 
          
    if a < 1.0:
      a += 0.02 
    if a > 1.0:
      a = 1.0            
    sfg.set_alpha(a)
    if a < 1.0:
     sbg.draw()  
    sfg.draw()`

**Comment by lutzh86** [comment] 2019-01-16 10:50
ok i fixed it for case: 

`def tex_load(fname):

  slide = Slide()
  if not os.path.isfile(fname):
    return None
  tex = pi3d.Texture(fname, blend=True, mipmap=False)
  xrat = 1
  yrat = 1
  slide.dimensions = (800, 480, 0, 0)
  slide.set_texture(tex)
  slide.set_alpha(0.0)
  slide.set_shader(shader)
  slide.positionZ(0.5)
  slide.set_2d_size(800, 480, 1,1)
  return slide`

**Comment by lutzh86** [comment] 2019-01-16 11:00
slide.set_2d_size(800, 480, 1,1) - no visible border on the bottom
  slide.set_2d_size(800, 480, 0,0) - visible border

**Comment by lutzh86** [comment] 2019-01-16 13:57
ok i will try to use sprites instead, too

i switched now over to TextBlock and got big performance increase.

but sadly, shadow cannot be set in TextBlock and not modified by regen?

**Comment by paddywwoof** [comment] 2019-01-16 16:23
I will re-issue the Slideshow_2d.py demo along the lines of the code below. What do you mean by the shadow not being set in TextBlock? Aren't those options part of the Font? I can see that the outlining is rather subtle but it seems to work ok in the SpriteMulti demo when I tried it. I will add a simplified TextBlock component to the code below later on tonight.

```
#!/usr/bin/python
from __future__ import absolute_import, division, print_function, unicode_literals

import os
import time
import random
import pi3d

TMDELAY = 5.0
DA = 0.01 # delta alpha
DIR = '/home/patrick/python/pi3d_demos/textures'

def tex_load(fname):
    tex = pi3d.Texture(fname, blend=True, m_repeat=True)
    slide = pi3d.ImageSprite(tex, shader=shader, camera=CAMERA,
                            w=DISPLAY.width, h=DISPLAY.height, z=0.5)
    slide.set_alpha(0.0)
    return slide

DISPLAY = pi3d.Display.create(background=(0.0, 0.0, 0.0, 1.0),
                                frames_per_second=20, tk=False, w=800, h=480)

shader = pi3d.Shader("uv_flat")
CAMERA = pi3d.Camera(is_3d=False)
nexttm = 0.0

iFiles = []
for f in os.listdir(DIR):
    fp = os.path.join(DIR, f)
    if os.path.isfile(fp): # could also check for type
        iFiles.append(fp)
random.shuffle(iFiles)
nFi = len(iFiles)
pic_num = 0
sfg = tex_load(iFiles[pic_num])

while DISPLAY.loop_running():
    tm = time.time()
    if tm > nexttm: # this must run first iteration of loop
        nexttm = tm + TMDELAY
        a = 0.0
        sbg = sfg
        sbg.positionZ(0.6)
        pic_num += 1
        if pic_num >= nFi:
            random.shuffle(iFiles)
            pic_num = 0
        sfg = tex_load(iFiles[pic_num])
          
    if a < 1.0:
        a += DA
        sbg.draw() # background only needs to be drawn if fg alpha < 1
    sfg.set_alpha(a)
    sfg.draw()
```

**Comment by lutzh86** [comment] 2019-01-16 16:44
from the "user-perspective" textblock is much more flexible, because u can change color, alpha etc. on the fly, without need loading multiple fonts.  except for shadow...  

because i need different "shadows" i need to load the same font twice. 


i got the ImageSprite  Sample working, but text ist only visible if i increase z from 0.5 to 2

**Comment by paddywwoof** [comment] 2019-01-16 19:09
@lutzh86 yes, the TextBlock, PointText system works by attaching a patch of texture to each vertex of an object. That way it's possible to do different things to each character and move them around etc. However it bundles a lot of additional info into the same 8 floats used for normal rendering. The result is that the RGBA are squashed into two floats of the normal and the size and z depth are squashed into the third. The way this is done is by using the whole number part and the fractional part. So the z value is rounded down to nearest whole number - i.e. 5.4 becomes 5.0 and the size goes from 0.0 to 0.99. So TLDR; make the z value of the text 1 and the z value of anything behind it 2 or larger.

Not sure what you mean by shadow here. are you rendering the same text twice, once in one colour with an offset or blur then over the top in a different colour? Anyway, if you can help find a good way to render clear text onto variable backgrounds that will be a good improvement to pi3d.

**Comment by paddywwoof** [comment] 2019-01-17 13:20
@lutzh86 yes, the TextBlock, PointText system works by attaching a patch of texture to each vertex of an object. That way it's possible to do different things to each character and move them around etc. However it bundles a lot of additional info into the same 8 floats used for normal rendering. The result is that the RGBA are squashed into two floats of the normal and the size and z depth are squashed into the third. The way this is done is by using the whole number part and the fractional part. So the z value is rounded down to nearest whole number - i.e. 5.4 becomes 5.0 and the size goes from 0.0 to 0.99. So TLDR; make the z value of the text 1 and the z value of anything behind it 2 or larger.

Not sure what you mean by shadow here. are you rendering the same text twice, once in one colour with an offset or blur then over the top in a different colour? Anyway, if you can help find a good way to render clear text onto variable backgrounds that will be a good improvement to pi3d.

EDIT - also noticed that the default Font behavior doesn't increase the point size automatically as space becomes available so [I've fixed this here.](https://github.com/tipam/pi3d/blob/develop/pi3d/util/Font.py#L111)

**Closed** 2019-01-30 16:21 UTC
